name: Jest Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install and test
      # runs a multi line script using "|"
      run: |
        echo 'installing...'
        npm install
        echo 'testing...'
        npm test
      env:
        CI: true
